language: objective-c
osx_image: xcode9.4
gemfile: Gemfile
bundler_args: "--without documentation --path bundle"
cache:
  bundler: true
  directories:
  - "/tmp/SwiftLint"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
script:
- "./Submodules/WeTransfer-iOS-CI/Scripts/travis.sh WeTransfer"
before_install:
- openssl aes-256-cbc -K $encrypted_fce2bbf28b94_key -iv $encrypted_fce2bbf28b94_iv
  -in WeTransferTests/Secrets.plist.enc -out WeTransferTests/Secrets.plist -d
